Automation and optimization work
getsolus/solus-appstream-data pull request #5
Opened 2024-10-29 15:47 UTC by sheepman4267

This is the (long-awaited) appstream automation PR!

Here's what it does:
- Adds an Ansible playbook which automates steps 1-5 of the current "Regenerating from teaparty server directly" workflow
- Optimizes the creation of appstream metadata by symlinking every package to be analyzed into one directory. This script:
  - Avoids analyzing packages we don't need to (-currently the script ignores -dbginfo packages, but should probably also ignore -devel ones). 
  - Only symlinks packages which are actually in the index, which works around https://github.com/getsolus/ferryd/issues/17.
 
 Here's what it doesn't include yet, which it needs to before this can be marked ready for review:
- A Taskfile with further automation, including steps 6-8 of the current instructions.
- Updates to README.md documenting the new process.
- A test plan in the description :)

2025-01-08 17:22 UTC, silkeh commented on inventory/hosts.yml.example
> +      # Set this to your username
Maybe it's better to recommend people to configure their username correctly in their SSH config so this file can be used as is?

For example:

```
Host *.getsol.us
  User <username here>
```

2025-01-08 17:22 UTC, silkeh commented on archive_screenshots.sh
> +#!/usr/bin/env bash
I recommend always adding this to reduce footgun potential:

```suggestion
#!/usr/bin/env bash
set -euo pipefail
```

2025-01-08 17:22 UTC, silkeh commented on setup_inventory.py
> +#!/bin/python3
If we go the `~/.ssh/config` route this should not be needed :S

2025-01-08 17:22 UTC, silkeh commented on create_symlinks.py
> +    # pprint(packages)
```suggestion
```

2025-01-08 17:22 UTC, silkeh commented on create_symlinks.py
> +    print('gothere')
:thinking:

2025-01-08 17:22 UTC, silkeh commented on create_symlinks.py
> +    print(eopkg_info)
```suggestion
```

2025-01-08 17:22 UTC, silkeh commented on create_symlinks.py
> +        return False
I think something like this should also work (syntax might not be exactly right though):
```suggestion
    return eopkg_info['name'] in eopkg_packages.keys() \
        and eopkg_info['release'] == eopkg_packages[eopkg_info['name']]) \
        and not eopkg_info['dbginfo']
```

2025-01-08 21:50 UTC, sheepman4267 commented on create_symlinks.py
> +    print('gothere')
Ha. Knew I'd miss at least one...

2025-01-08 21:51 UTC, sheepman4267 commented on create_symlinks.py
> +    # pprint(packages)
Done.

2025-01-08 21:51 UTC, sheepman4267 commented on create_symlinks.py
> +    print(eopkg_info)
Also done.

2025-01-08 21:56 UTC, sheepman4267 commented on inventory/hosts.yml.example
> +      # Set this to your username
Good idea, but I think it's out of scope here. I think this should be part of our staff onboarding processes, which should be written down (what people need access to, why, how to get there, etc.). If that exists, I've never seen it (at least, not in the "set up your SSH config correctly" level of detail). If we can get that documentation into shape in an appropriate place, I'd love to remove this hacky inventory creation script nonsense. I'm just not convinced that the correct place is here in this repo. 

Feel free to convince me otherwise, though!

2025-01-08 21:57 UTC, sheepman4267 commented on create_symlinks.py
> +        return False
That is much cleaner, yes. I'll review the syntax in detail when I'm not at work.

2025-01-09 21:24 UTC, silkeh commented on inventory/hosts.yml.example
> +      # Set this to your username
I didn't mean to suggest to document that *here*, I just don't think that this project should carry the complexity burden of people not having configured their SSH correctly.

2025-01-11 02:38 UTC, TraceyC77 requested changes
The README needs a step before generating mainstream data about copying hosts.yml.example to the real file and adding the username. Otherwise go-task full-process errors out. Once that's done this PR is good to go.

In my testing, once I set that up and ran go-task full-process, appstream data generation was successful

2025-01-11 02:38 UTC, TraceyC77 commented on README.md
> +3. Run `go-task appstream-init`. This task will install `pyyaml` and `ansible` on your system, and then install the necessary ansible collection.
There needs to be a step here to copy and adapt `inventory.yml.example` and that the file needs to be named `hosts.yml` (due to the rule in `.gitignore`)

2025-01-11 02:53 UTC, sheepman4267 commented on README.md
> +3. Run `go-task appstream-init`. This task will install `pyyaml` and `ansible` on your system, and then install the necessary ansible collection.
I've removed the rule in .gitignore and made the inventory file generic. A username does not need to be listed there if your SSH is configured correctly, per the conversation with @silkeh.

2025-01-11 03:45 UTC, TraceyC77 approved these changes
I re-tested after doing a hard reset on my local copy of the branch so I had the new generic hosts.yml. I already had an entry for teaparty in `~/.ssh.config`. 
Verified that appstream data was able to be kicked off an a commit with the data was created as expected.

I Silke's concerns have also been addressed.

Good to go!

2025-01-11 03:59 UTC, merged